python3 training_pipeline.py with _folder=1
python3 training_pipeline.py with _folder=2
python3 training_pipeline.py with _folder=3
python3 training_pipeline.py with _folder=4
python3 training_pipeline.py with _folder=5
python3 training_pipeline.py with _folder=6
python3 training_pipeline.py with _folder=7
python3 training_pipeline.py with _folder=8
python3 training_pipeline.py with _folder=9
python3 training_pipeline.py with _folder=10
python3 training_pipeline.py with _folder=1 _model_name=mobilenet-v3 _comb_config=[32,768]
python3 training_pipeline.py with _folder=2 _model_name=mobilenet-v3 _comb_config=[32,768]
python3 training_pipeline.py with _folder=3 _model_name=mobilenet-v3 _comb_config=[32,768]
python3 training_pipeline.py with _folder=4 _model_name=mobilenet-v3 _comb_config=[32,768]
python3 training_pipeline.py with _folder=5 _model_name=mobilenet-v3 _comb_config=[32,768]
python3 training_pipeline.py with _folder=6 _model_name=mobilenet-v3 _comb_config=[32,768]
python3 training_pipeline.py with _folder=7 _model_name=mobilenet-v3 _comb_config=[32,768]
python3 training_pipeline.py with _folder=8 _model_name=mobilenet-v3 _comb_config=[32,768]
python3 training_pipeline.py with _folder=9 _model_name=mobilenet-v3 _comb_config=[32,768]
python3 training_pipeline.py with _folder=10 _model_name=mobilenet-v3 _comb_config=[32,768]
python3 training_pipeline.py with _folder=1 _model_name=davit_tiny _comb_config=[24,768]
python3 training_pipeline.py with _folder=2 _model_name=davit_tiny _comb_config=[24,768]
python3 training_pipeline.py with _folder=3 _model_name=davit_tiny _comb_config=[24,768]
python3 training_pipeline.py with _folder=4 _model_name=davit_tiny _comb_config=[24,768]
python3 training_pipeline.py with _folder=5 _model_name=davit_tiny _comb_config=[24,768]
python3 training_pipeline.py with _folder=6 _model_name=davit_tiny _comb_config=[24,768]
python3 training_pipeline.py with _folder=7 _model_name=davit_tiny _comb_config=[24,768]
python3 training_pipeline.py with _folder=8 _model_name=davit_tiny _comb_config=[24,768]
python3 training_pipeline.py with _folder=9 _model_name=davit_tiny _comb_config=[24,768]
python3 training_pipeline.py with _folder=10 _model_name=davit_tiny _comb_config=[24,768]
python3 training_pipeline.py with _folder=1 _model_name=caformer_s18 _comb_config=[16,768]
python3 training_pipeline.py with _folder=2 _model_name=caformer_s18 _comb_config=[16,768]
python3 training_pipeline.py with _folder=3 _model_name=caformer_s18 _comb_config=[16,768]
python3 training_pipeline.py with _folder=4 _model_name=caformer_s18 _comb_config=[16,768]
python3 training_pipeline.py with _folder=5 _model_name=caformer_s18 _comb_config=[16,768]
python3 training_pipeline.py with _folder=6 _model_name=caformer_s18 _comb_config=[16,768]
python3 training_pipeline.py with _folder=7 _model_name=caformer_s18 _comb_config=[16,768]
python3 training_pipeline.py with _folder=8 _model_name=caformer_s18 _comb_config=[16,768]
python3 training_pipeline.py with _folder=9 _model_name=caformer_s18 _comb_config=[16,768]
python3 training_pipeline.py with _folder=10 _model_name=caformer_s18 _comb_config=[16,768]
python3 training_pipeline.py with _folder=1 _model_name=efficientnet-b4 _comb_config=[56,768]
python3 training_pipeline.py with _folder=2 _model_name=efficientnet-b4 _comb_config=[56,768]
python3 training_pipeline.py with _folder=3 _model_name=efficientnet-b4 _comb_config=[56,768]
python3 training_pipeline.py with _folder=4 _model_name=efficientnet-b4 _comb_config=[56,768]
python3 training_pipeline.py with _folder=5 _model_name=efficientnet-b4 _comb_config=[56,768]
python3 training_pipeline.py with _folder=6 _model_name=efficientnet-b4 _comb_config=[56,768]
python3 training_pipeline.py with _folder=7 _model_name=efficientnet-b4 _comb_config=[56,768]
python3 training_pipeline.py with _folder=8 _model_name=efficientnet-b4 _comb_config=[56,768]
python3 training_pipeline.py with _folder=9 _model_name=efficientnet-b4 _comb_config=[56,768]
python3 training_pipeline.py with _folder=10 _model_name=efficientnet-b4 _comb_config=[56,768]
python3 training_pipeline.py with _folder=1 _model_name=maxvit_tiny _comb_config=[16,768]
python3 training_pipeline.py with _folder=2 _model_name=maxvit_tiny _comb_config=[16,768]
python3 training_pipeline.py with _folder=3 _model_name=maxvit_tiny _comb_config=[16,768]
python3 training_pipeline.py with _folder=4 _model_name=maxvit_tiny _comb_config=[16,768]
python3 training_pipeline.py with _folder=5 _model_name=maxvit_tiny _comb_config=[16,768]
python3 training_pipeline.py with _folder=6 _model_name=maxvit_tiny _comb_config=[16,768]
python3 training_pipeline.py with _folder=7 _model_name=maxvit_tiny _comb_config=[16,768]
python3 training_pipeline.py with _folder=8 _model_name=maxvit_tiny _comb_config=[16,768]
python3 training_pipeline.py with _folder=9 _model_name=maxvit_tiny _comb_config=[16,768]
python3 training_pipeline.py with _folder=10 _model_name=maxvit_tiny _comb_config=[16,768]
python3 training_pipeline.py with _folder=1 _model_name=mvitv2_small _comb_config=[24,768]
python3 training_pipeline.py with _folder=2 _model_name=mvitv2_small _comb_config=[24,768]
python3 training_pipeline.py with _folder=3 _model_name=mvitv2_small _comb_config=[24,768]
python3 training_pipeline.py with _folder=4 _model_name=mvitv2_small _comb_config=[24,768]
python3 training_pipeline.py with _folder=5 _model_name=mvitv2_small _comb_config=[24,768]
python3 training_pipeline.py with _folder=6 _model_name=mvitv2_small _comb_config=[24,768]
python3 training_pipeline.py with _folder=7 _model_name=mvitv2_small _comb_config=[24,768]
python3 training_pipeline.py with _folder=8 _model_name=mvitv2_small _comb_config=[24,768]
python3 training_pipeline.py with _folder=9 _model_name=mvitv2_small _comb_config=[24,768]
python3 training_pipeline.py with _folder=10 _model_name=mvitv2_small _comb_config=[24,768]